// Icon shim: the app imports icons by their old lucide names, but they are now
// backed by Shopify Polaris icons. Each export is a small wrapper that forwards
// className, defaults a size, and uses currentColor so existing `h-4 w-4 text-*`
// usages keep working unchanged. `pick()` falls back gracefully if a Polaris
// name isn't available in the installed version.
import * as P from '@shopify/polaris-icons'
import { cn } from '../../utils/cn'

const FALLBACK = P.NoteIcon
const pick = (...names) => {
  for (const n of names) if (P[n]) return P[n]
  return FALLBACK
}

const wrap = (Ico) => function Icon({ className = '', ...props }) {
  const sized = /\b[wh]-/.test(className) ? className : cn('h-5 w-5', className)
  return <Ico className={cn('fill-current', sized)} {...props} />
}

export const AlertCircle = wrap(pick('AlertCircleIcon'))
export const AlertTriangle = wrap(pick('AlertTriangleIcon', 'AlertDiamondIcon'))
export const Archive = wrap(pick('ArchiveIcon', 'OrderIcon'))
export const ArrowLeft = wrap(pick('ArrowLeftIcon'))
export const AtSign = wrap(pick('AtSignIcon', 'EmailIcon'))
export const BadgeCheck = wrap(pick('CheckCircleIcon'))
export const Ban = wrap(pick('DisabledIcon'))
export const Banknote = wrap(pick('CashRupeeIcon', 'CashDollarIcon'))
export const BarChart2 = wrap(pick('ChartVerticalIcon'))
export const BatteryCharging = wrap(pick('BatteryIcon', 'WandIcon'))
export const Bell = wrap(pick('NotificationIcon', 'AlertBubbleIcon'))
export const BellRing = wrap(pick('NotificationIcon', 'AlertBubbleIcon'))
export const Building2 = wrap(pick('StoreIcon'))
export const Calendar = wrap(pick('CalendarIcon'))
export const Camera = wrap(pick('CameraIcon'))
export const Car = wrap(pick('DeliveryIcon'))
export const Check = wrap(pick('CheckIcon'))
export const CheckCheck = wrap(pick('CheckIcon'))
export const CheckCircle = wrap(pick('CheckCircleIcon'))
export const CheckCircle2 = wrap(pick('CheckCircleIcon'))
export const ChevronDown = wrap(pick('ChevronDownIcon'))
export const ChevronLeft = wrap(pick('ChevronLeftIcon'))
export const ChevronRight = wrap(pick('ChevronRightIcon'))
export const ChevronsLeft = wrap(pick('ChevronLeftIcon'))
export const ChevronsUpDown = wrap(pick('SelectIcon', 'SortIcon'))
export const Clock = wrap(pick('ClockIcon'))
export const CloudRain = wrap(pick('WeatherIcon'))
export const Coins = wrap(pick('CashDollarIcon'))
export const Copy = wrap(pick('DuplicateIcon', 'ClipboardIcon'))
export const CornerUpLeft = wrap(pick('ReplyIcon', 'ArrowLeftIcon'))
export const CreditCard = wrap(pick('CreditCardIcon', 'PaymentIcon'))
export const DollarSign = wrap(pick('CashDollarIcon'))
export const Download = wrap(pick('ExportIcon', 'ArrowDownIcon'))
export const Edit = wrap(pick('EditIcon'))
export const Eye = wrap(pick('ViewIcon'))
export const EyeOff = wrap(pick('HideIcon'))
export const FileText = wrap(pick('NoteIcon', 'PageIcon'))
export const GitCompare = wrap(pick('TransferIcon'))
export const History = wrap(pick('HistoryIcon', 'ClockIcon'))
export const Inbox = wrap(pick('InboxIcon', 'EmailIcon'))
export const Info = wrap(pick('InfoIcon', 'AlertCircleIcon'))
export const Landmark = wrap(pick('BankIcon'))
export const LayoutGrid = wrap(pick('HomeIcon'))
export const Leaf = wrap(pick('LeafIcon', 'WandIcon'))
export const Lock = wrap(pick('LockIcon'))
export const LogOut = wrap(pick('ExitIcon', 'PersonExitIcon'))
export const Mail = wrap(pick('EmailIcon'))
export const MapPin = wrap(pick('LocationIcon', 'PinIcon'))
export const Megaphone = wrap(pick('MegaphoneIcon'))
export const Menu = wrap(pick('MenuIcon'))
export const MessageSquare = wrap(pick('ChatIcon'))
export const Mic = wrap(pick('MicrophoneIcon'))
export const MicOff = wrap(pick('MicrophoneIcon'))
export const Monitor = wrap(pick('DesktopIcon'))
export const Moon = wrap(pick('MoonIcon'))
export const Navigation = wrap(pick('LocationIcon', 'CompassIcon'))
export const Paperclip = wrap(pick('AttachmentIcon', 'NoteIcon'))
export const Pause = wrap(pick('PauseCircleIcon'))
export const Pencil = wrap(pick('EditIcon'))
export const Phone = wrap(pick('PhoneIcon'))
export const PhoneOff = wrap(pick('PhoneIcon'))
export const Play = wrap(pick('PlayIcon', 'PlayCircleIcon'))
export const Plus = wrap(pick('PlusIcon'))
export const Repeat = wrap(pick('OrderRepeatIcon', 'RefreshIcon'))
export const Ruler = wrap(pick('MeasurementIcon', 'NoteIcon'))
export const Save = wrap(pick('SaveIcon'))
export const Search = wrap(pick('SearchIcon'))
export const Send = wrap(pick('SendIcon'))
export const Settings = wrap(pick('SettingsIcon', 'ThemeIcon'))
export const Shield = wrap(pick('ShieldCheckMarkIcon', 'ShieldIcon'))
export const ShieldCheck = wrap(pick('ShieldCheckMarkIcon', 'ShieldIcon'))
export const Siren = wrap(pick('AlertTriangleIcon', 'AlertDiamondIcon'))
export const Star = wrap(pick('StarIcon'))
export const Sun = wrap(pick('SunIcon'))
export const Timer = wrap(pick('ClockIcon'))
export const ToggleLeft = wrap(pick('ToggleOffIcon', 'DisabledIcon'))
export const ToggleRight = wrap(pick('ToggleOnIcon', 'CheckCircleIcon'))
export const Trash2 = wrap(pick('DeleteIcon'))
export const TrendingUp = wrap(pick('ChartVerticalIcon', 'ArrowUpIcon'))
export const User = wrap(pick('PersonIcon', 'ProfileIcon'))
export const UserCheck = wrap(pick('PersonIcon', 'ProfileIcon'))
export const UserX = wrap(pick('PersonRemoveIcon'))
export const Users = wrap(pick('TeamIcon', 'PersonIcon'))
export const Video = wrap(pick('CameraIcon'))
export const VideoOff = wrap(pick('CameraIcon'))
export const Wallet = wrap(pick('WalletIcon', 'CashDollarIcon'))
export const X = wrap(pick('XIcon'))
export const XCircle = wrap(pick('XCircleIcon'))
export const Zap = wrap(pick('WandIcon', 'FlashlightIcon'))
